package consts.navbarstore;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum NavBarStoreCategory {
    FREE_TO_PLAY("Free"),
    DEMOS("demos"),
    EARLY_ACCESS("Early"),
    STEAM_DECK("steamdeck"),
    GREAT_ON_DECK("greatondeck"),
    CONTROLLER_FRIENDLY("controller"),
    REMOTE_PLAY("remoteplay_hub"),
    VR_TITLES("/vr/"),
    VR_HARDWARE("vrhardware"),
    SOFTWARE("software"),
    SOUNDTRACKS("soundtracks"),
    MAC_OS("macos"),
    STEAM_OS_AND_LINUX("linux"),
    FOR_PC_CAFES("pccafe"),
    ACTION("/action/"),
    ARCADE_AND_RHYTHM("arcade_rhythm"),
    FIGHTING_AND_MARTIAL_ARTS("fighting_martial"),
    FIRST_PERSON_SHOOTER("action_fps"),
    HACK_AND_SLASH("hack_and_slash"),
    PLATFORMER_AND_RUNNER("action_run_jump"),
    THIRD_PERSON_SHOOTER("action_tps"),
    SHMUP("shmup"),
    ADVENTURE("/adventure/"),
    ADVENTURE_RPG("adventure_rpg"),
    CASUAL("casual"),
    HIDDEN_OBJECT("hidden_object"),
    METROIDVANIA("metroidvania"),
    PUZZLE("puzzle_matching"),
    STORY_RICH("story_rich"),
    VISUAL_NOVEL("visual_novel"),
    ROLE_PLAYING("/rpg/"),
    ACTION_RPG("rpg_action"),
    JRPG("rpg_jrpg"),
    PARTY_BASED("rpg_party_based"),
    ROGUE_LIKE("rogue_like_rogue_lite"),
    STRATEGY_RPG("rpg_strategy_tactics"),
    TURN_BASED("rpg_turn_based"),
    SIMULATION("simulation"),
    BUILDING_AND_AUTOMATION("sim_building_automation"),
    DATING("sim_dating"),
    FARMING_AND_CRAFTING("sim_farming_crafting"),
    HOBBY_AND_JOB("sim_hobby_sim"),
    LIFE_AND_IMMERSIVE("sim_life"),
    SANDBOX_AND_PHYSICS("sim_physics_sandbox"),
    SPACE_AND_FLIGHT("sim_space_flight"),
    STRATEGY("/strategy/"),
    CARD_AND_BOARD("strategy_card_board"),
    CITY_AND_SETTLEMENT("strategy_cities_settlements"),
    GRAND_AND_4_X("strategy_grand_4x"),
    MILITARY("strategy_military"),
    REAL_TIME_STRATEGY("strategy_real_time"),
    TOWER_DEFENSE("tower_defense"),
    TURN_BASED_STRATEGY("strategy_turn_based"),
    SPORTS_AND_RACING("sports_and_racing"),
    ALL_SPORTS("/sports/"),
    FISHING_AND_HUNTING("sports_fishing_hunting"),
    INDIVIDUAL_SPORTS("sports_individual"),
    RACING("/racing/"),
    RACING_SIM("racing_sim"),
    SPORTS_SIM("sports_sim"),
    TEAM_SPORTS("sports_team"),
    ANIME("anime"),
    HORROR("horror"),
    MYSTERY_AND_DETECTIVE("mystery_detective"),
    OPEN_WORLD("exploration_open_world"),
    SCI_FI_AND_CYBERPUNK("science_fiction"),
    SPACE("space"),
    SURVIVAL("survival"),
    CO_OPERATIVE("multiplayer_coop"),
    LAN("multiplayer_lan"),
    LOCAL_AND_PARTY("multiplayer_local_party"),
    MMO("multiplayer_mmo"),
    MULTIPLAYER("/multiplayer/"),
    ONLINE_COMPETITIVE("multiplayer_online_competitive"),
    SINGLEPLAYER("singleplayer");


    public final String label;
}
